- name: installing multiple packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages using loops
    ansible.builtin.packages:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'nginx', state: 'present'}